---

- name: decide mig_arch
  set_fact:
    mig_arch: amd64
  when: ansible_architecture == 'x86_64'
- set_fact:
    mig_sys: linux
  when: ansible_system == 'Linux'
- set_fact:
    mig_sys: windows
  when: ansible_system == 'Windows'

- name: decide mig_agent_bin
  set_fact:
    mig_agent_bin: "{{ mig_src }}/{{ mig_sys }}/{{ mig_arch }}/mig-agent-latest"
  when: ansible_system != 'Windows'
- set_fact:
    mig_agent_bin: "{{ mig_src }}/{{ mig_sys }}/{{ mig_arch }}/mig-agent-latest.exe"
  when: ansible_system == 'Windows'

- name: decide mig_agent_pkg
  set_fact:
    mig_agent_pkg: "{{ mig_src }}/mig-agent_latest-{{ ansible_architecture }}.deb"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- set_fact:
    mig_agent_pkg: "{{ mig_src }}/mig-agent-latest-{{ ansible_architecture }}.rpm"
  when: (ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: retrieve mig-agent archive if remote on orchestrator
  fetch: src="{{ mig_agent_pkg }}" dest=tmp/ flat=yes
  delegate_to: "{{ mig_servername }}"
  when: mig_api_host != 'localhost'
- name: push mig-agent on host
  copy: "src=tmp/{{ mig_agent_pkg | basename }} dest=/root/{{ mig_agent_pkg | basename }} mode=644"
  when: mig_api_host != 'localhost'
- set_fact:
    mig_agent_pkg: "/root/{{ mig_agent_pkg | basename }}"
  when: mig_api_host != 'localhost'

## FIXME! handle package update? latest not supported for pkg file
- name: apt | mig-agent install
  apt: deb="{{ mig_agent_pkg }}" state=present
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- name: yum | mig-agent install
  yum: name="{{ mig_agent_pkg }}" state=present
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## debian /agent_install.sh
- name: get mig-agent path
  shell: "ls /sbin/mig-agent-*"
  changed_when: false
  register: migagentpath
- name: check mig-agent permissions
  file: dest="{{ migagentpath.stdout }}" mode=0500 owner=root group=root state=file
- name: symlink last mig-agent
  file: src="{{ migagentpath.stdout }}" dest=/sbin/mig-agent state=link
#- name: execute mig-agent
#  command: "/sbin/mig-agent -d"
#  ignore_errors: true
## FIXME! missing services/supervisor config

## FIXME! builtin config seems incorrect
- stat: path={{ mig_src }}/conf/mig-agent.cfg
  register: macfg
- debug: var=macfg
- name: setting separate mig-agent config file
  copy: 
    src: "{{ mig_src }}/conf/mig-agent.cfg"
    dest: /etc/mig/mig-agent.cfg
    mode: '0600'
    remote_src: true

- name: set supervisor config to manage MIG client
  template: src=supervisord-migagent.ini dest={{ supervisor_confdir }}/migagent.{{ supervisor_ext }} mode=0644
  notify:
    - restart supervisor


