---
## from mhn/honeymap

## recent golang?
## alternative? https://launchpad.net/~evarlast/+archive/ubuntu/golang1.4
- set_fact:
    architecture: 386
  when: ansible_architecture == 'i386'
- set_fact:
    architecture: amd64
  when: ansible_architecture == 'x86_64'
- stat: path=/usr/local/go{{ mig_gover }}.linux-{{ architecture }}.tar.gz
  register: goarchive
- name: download recent golang
  get_url: url=https://storage.googleapis.com/golang/go{{ mig_gover }}.linux-{{ architecture }}.tar.gz dest=/usr/local/go{{ mig_gover }}.linux-{{ architecture }}.tar.gz mode=0440
  when: not goarchive.stat.exists
- stat: path=/usr/local/go
  register: godir
- name: Extract go archive to /usr/local
#  command: tar xzf /usr/local/go{{ mig_gover }}.linux-{{ architecture }}.tar.gz -C /usr/local/
  unarchive: "src=/usr/local/go{{ mig_gover }}.linux-{{ architecture }}.tar.gz dest=/usr/local/ copy=no"
  when: not godir.stat.exists

- file: src=/usr/local/go/bin/{{ item }} dest=/usr/bin/{{ item }} state=link
  with_items:
    - go
    - godoc
    - gofmt

