---

- set_fact:
    mig_url: "http://{{ mig_api_host }}"
  when: not (mig_nginx_use_ssl is defined and mig_nginx_use_ssl)
- set_fact:
    mig_url: "https://{{ mig_api_host }}"
  when: mig_nginx_use_ssl is defined and mig_nginx_use_ssl

- include: server.yml
  when: mig_mode == 'server'

- include: client.yml
  when: mig_mode == 'client' or (mig_server_withagent is defined and mig_server_withagent)

